version: '3.4'

services:
  firstapi:
    image: firstapi
    restart: always
    ports:
      - 3000:3000
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
